name: Tests
on: [pull_request]
jobs:
  unit:
    name: Unit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Build
        run: |
          cp -r build/tests/* .
          docker-compose build
      - name: Run tests
        run: |
          docker-compose up --exit-code-from botpress

  e2e:
    name: e2e
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '12.13.0'
      - name: Fetch Node Packages
        run: |
          yarn
      - name: Get NLU Binary
        run: |
          wget https://github.com/botpress/nlu/releases/download/v0.0.1-rc.3/nlu-v0_0_1-linux-x64
          chmod +x ./nlu-v0_0_1-linux-x64
          echo "hello world #1"
          ls -la
          ./nlu-v0_0_1-linux-x64 --help
          echo "hello world #2"
      - name: Build core, UI and modules
        run: |
          NODE_OPTIONS="--max-old-space-size=6000" yarn build
      - name: Run Tests
        run: |
          NLU_BIN_DIR="." yarn start & sleep 5s &&
          HEADLESS=true JEST_TIMEOUT=30000 yarn itest
      - name: Upload Screenshots
        uses: actions/upload-artifact@master
        if: failure()
        with:
          name: screenshots
          path: build/tests/e2e/screenshots
